name: PlatformIO CI

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'specify firmware version tag'
        required: true
        type: string
      ftpTarget:
        description: 'specify firmware target on FTP Server'
        default: '/'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Validate tag
        run: |
          validate_tag() {
            local tag="$1"
            if [[ "$tag" =~ ^v[0-9]+\.[0-9]+\.[0-9][0-9]+\.([a-z0-9]{7})$ ]]; then
              return 0
            else
              return 1
            fi
          }    
          if ! validate_tag "${{ inputs.tag }}"; then
            echo "Errore: il tag '${{ inputs.tag }}' non è valido. Deve rispettare il formato v2.5.19.d5cd6f8."
            exit 1
          else
            echo "Il tag '${{ inputs.tag }}' è valido."
          fi

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Fetch Tags from Upstream
        run: |
          git remote add upstream https://github.com/meshtastic/firmware.git
          git fetch upstream

      - name: Checkout Code for Target Tag
        run: |
          git checkout "tags/${{ inputs.tag }}"

      - name: Checkout Patch Files
        run: |
          git fetch origin "refs/tags/patches-${{ inputs.tag }}:refs/tags/patches-${{ inputs.tag }}"
          git checkout "patches-${{ inputs.tag }}" -- *.patch

      - name: Apply Patches
        run: |
          for patch in *.patch; do
            if git apply "$patch"; then
              echo "Patch $patch applicato con successo."
            else
              echo "Errore: il patch $patch non è applicabile."
              exit 1
            fi
          done