name: PlatformIO CI

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'specify firmware version tag'
        required: true
        type: choice
        options:
        - v2.7.19.bb3d6d5
        - v2.7.15.567b8ea
        - v2.7.13.597fa0b
        - v2.7.11.ee68575
        - v2.7.4.c1f4f79
        - v2.6.10.9ce4455
        - v2.6.7.2d6181f
        - v2.6.2.31c0e8f
        - v2.5.23.bf958ed 
        - v2.5.20.4c97351
        - v2.5.19.f9876cf
        - v2.5.18.89ebafc
        - v2.5.15.79da236
      boards:
        description: 'enter boards to compile for'
        required: true
        type: string
  repository_dispatch:
    types: firmware-build-request      

env: 
  TAG: ${{ inputs.tag || github.event.client_payload.tag }}
  BOARDS: ${{ inputs.boards || github.event.client_payload.boards }}

jobs:
  build:
    runs-on: LoraItalia

    steps:
      # - name: Send email on compilation start with payload content
      #   uses: dawidd6/action-send-mail@v4
      #   if: ${{ github.event_name == 'repository_dispatch' }}
      #   with:
      #     server_address: ${{secrets.MAIL_SERVER}}
      #     server_port: 465
      #     username: ${{secrets.MAIL_USERNAME}}
      #     password: ${{secrets.MAIL_PASSWORD}}
      #     subject: Github Action Test
      #     to: ***@gmail.com
      #     from: LoraItalia automated custom compiler
      #     body: "Starting your custom compilation with parameters: ${{ github.event.client_payload}}"

      # - name: End if run by dispatch
      #   if: ${{ github.event_name == 'repository_dispatch' }}
      #   run: exit 1
        
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Fetch Tags from Upstream
        run: |
          git remote remove upstream || true
          git remote add upstream https://github.com/meshtastic/firmware.git
          git fetch upstream

      - name: Checkout Code for Target Tag
        run: |
          git checkout "tags/$TAG"

      - name: Checkout Patch Files
        run: |
          git fetch origin "refs/tags/patches-$TAG:refs/tags/patches-$TAG"
          git checkout "patches-$TAG" -- *.patch

      - name: Apply Patches
        run: |
          for patch in *.patch; do
            if git apply "$patch"; then
              echo "Patch $patch applicato con successo."
            else
              echo "Errore: il patch $patch non è applicabile."
              exit 1
            fi
          done

      - name: Add boards
        run: sed -i "/^default_envs =/c\default_envs = $BOARDS" platformio.ini

      # - name: Add users preferences to userPrefs.jsonc
      #   if: ${{ github.event_name == 'repository_dispatch' }}
      #   run: |
      #     if [[ -n "${{ github.event.client_payload.userprefs.long_name}}" ]]; then
      #       sed -i -E "s|^[[:space:]]*// *\"USERPREFS_CONFIG_OWNER_LONG_NAME\".*|\"USERPREFS_CONFIG_OWNER_LONG_NAME\": \"${{ github.event.client_payload.userprefs.long_name}}\",|" userPrefs.jsonc
      #     else
      #       echo "LONG_NAME is not present"
      #     fi
      #     if [[ -n "${{ github.event.client_payload.userprefs.short_name}}" ]]; then
      #       sed -i -E "s|^[[:space:]]*// *\"USERPREFS_CONFIG_OWNER_SHORT_NAME\".*|\"USERPREFS_CONFIG_OWNER_SHORT_NAME\": \"${{ github.event.client_payload.userprefs.short_name}}\",|" userPrefs.jsonc
      #     else
      #       echo "SHORT_NAME is not present"
      #     fi
      #     if [[ -n "${{ github.event.client_payload.userprefs.modem_preset}}" ]]; then
      #       sed -i -E "s|^[[:space:]]*// *\"USERPREFS_LORACONFIG_MODEM_PRESET\".*|\"USERPREFS_LORACONFIG_MODEM_PRESET\": \"${{ github.event.client_payload.userprefs.modem_preset}}\",|" userPrefs.jsonc
      #     else
      #       echo "MODEM_PRESET is not present"
      #     fi
      #     if [[ -n "${{ github.event.client_payload.userprefs.lora_region}}" ]]; then
      #       sed -i -E "s|^[[:space:]]*// *\"USERPREFS_CONFIG_LORA_REGION\".*|\"USERPREFS_CONFIG_LORA_REGION\": \"${{ github.event.client_payload.userprefs.lora_region}}\",|" userPrefs.jsonc
      #     else
      #       echo "LORA_REGION is not present"
      #     fi
      #     cat userPrefs.jsonc
      - name: Add user preferences to userPrefs.jsonc
        if: ${{ github.event_name == 'repository_dispatch' }}
        run: |
          echo '${{ toJSON(github.event.client_payload.userprefs) }}' | jq -r 'to_entries | .[] | "\(.key)=\(.value)"' | while IFS='=' read -r key value; do
            # Use sed to modify userPrefs.jsonc file
            sed -i -E "s|^[[:space:]]*// *\"$key\".*|\"$key\": \"$value\",|" userPrefs.jsonc
          done
          cat userPrefs.jsonc

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}-pio-${{ hashFiles('platformio.ini') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-pio-

      - name: Read version from file
        id: get_version
        run: |
          version=$(grep -oP '(?<=major = )\d+' version.properties).$(grep -oP '(?<=minor = )\d+' version.properties).$(grep -oP '(?<=build = )\d+' version.properties)
          commit_hash=$(git rev-parse --short HEAD)
          echo "VERSION_TAG=$version-$commit_hash" >> $GITHUB_ENV

      - name: Install PlatformIO Core
        run: pip install --upgrade --cache-dir ~/.cache/pip platformio

      - name: Build PlatformIO Project
        run: pio run

      - name: Create folder with builds
        run: |
          mkdir artifacts
          mkdir artifacts/firmware-${{ env.VERSION_TAG }}

      - name: Copy compiled binaries
        run: |
          for board in $(echo "$BOARDS" | tr ',' ' '); do
            mkdir artifacts/firmware-${{ env.VERSION_TAG }}/$board
            cp .pio/build/$board/firmware.bin artifacts/firmware-${{ env.VERSION_TAG }}/$board/firmware.${{ env.VERSION_TAG }}.update.bin || true
            cp .pio/build/$board/firmware.factory.bin artifacts/firmware-${{ env.VERSION_TAG }}/$board/firmware.${{ env.VERSION_TAG }}.factory.bin || true
            cp .pio/build/$board/firmware.uf2 artifacts/firmware-${{ env.VERSION_TAG }}/$board/firmware.${{ env.VERSION_TAG }}.uf2 || true
            cp .pio/build/$board/firmware.zip artifacts/firmware-${{ env.VERSION_TAG }}/$board/firmware.${{ env.VERSION_TAG }}.zip || true
          done

      - name: Upload FTP
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: "artifacts/"
          server-dir: "${{ inputs.ftpTarget }}"

      - name: Upload FTP
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: sebastianpopp/ftp-action@releases/v2
        with:
          host: ${{ secrets.FTP_HOST }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          localDir: "artifacts/"
          remoteDir: "/"

      - name: Trigger Fw move
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          curl -X GET https://www.loraitalia.it/movefw.php

      - name: Zip firmware
        if: ${{ github.event_name == 'repository_dispatch' }}
        run: |
          cd artifacts
          zip -r firmware.zip firmware-${{ env.VERSION_TAG }}
          cd ..

      - name: Mask Email
        if: failure() || github.event_name == 'repository_dispatch'
        run: |
          TO_EMAIL=$(jq -r '.client_payload.email' $GITHUB_EVENT_PATH)
          echo ::add-mask::$TO_EMAIL
          echo TO_EMAIL=$TO_EMAIL >> $GITHUB_ENV

      - name: Send Email with zipped firmware
        if: ${{ github.event_name == 'repository_dispatch' }}
        uses: dawidd6/action-send-mail@v4
        with:
          server_address: ${{secrets.MAIL_SERVER}}
          server_port: 587
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          ignore_cert: true
          subject: LoraItalia Firmware ${{ env.TAG }} for ${{ env.BOARDS }}
          to: ${{ env.TO_EMAIL }}
          from: LoraItalia automated Builder
          body: "The firmware build for ${{ env.BOARDS }} version ${{ env.TAG }} has finished, you can find it as attachment"
          attachments: artifacts/firmware.zip

      - name: Send notification email on failure
        if: failure() && github.event_name == 'repository_dispatch'
        uses: dawidd6/action-send-mail@v4
        with:
          server_address: ${{secrets.MAIL_SERVER}}
          server_port: 587
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          ignore_cert: true
          subject: LoraItalia Firmware BUILD ERROR
          to: ${{ env.TO_EMAIL }}
          from: LoraItalia automated Builder
          body: "The firmware build has failed, please ask for support here https://t.me/meshtastic_italia_community"
  
